#!/usr/bin/env bash
# Install Broz OS into every tool listed in targets.conf.
#
# Why this exists: TICKET-US-018 hand-copied 18 command files out of a clone and
# deleted the clone. Nothing noticed, because the acceptance check counted files
# instead of resolving what they pointed at. Everything installed here is a
# generated artifact -- if it drifts or vanishes, re-run this.
#
#   ./install.sh          install/refresh, preserving hand-edited shims
#   ./install.sh --force  overwrite hand-edited shims too
#   ./install.sh --check  report drift, change nothing (exit 1 if any)
#
# See SHIMS.md for how the shims work and which vendor docs each choice follows.
set -euo pipefail

BROZ_HOME="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SRC="$BROZ_HOME/commands/broz"
CONF="$BROZ_HOME/targets.conf"
SKCONF="$BROZ_HOME/skills.conf"
MARKER="<!-- generated by ~/.slopdog/install.sh -- edit the source in ~/.slopdog/commands/broz/ -->"

FORCE=0; CHECK=0
for a in "$@"; do
  case "$a" in
    --force) FORCE=1 ;;
    --check) CHECK=1 ;;
    -h|--help) sed -n '2,14p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *) echo "unknown flag: $a" >&2; exit 2 ;;
  esac
done

[[ -d "$SRC" ]] || { echo "no command source at $SRC" >&2; exit 1; }
[[ -f "$CONF" ]] || { echo "no targets.conf at $CONF" >&2; exit 1; }

drift=0

# Render one source command for one tool.
#
# claude: YAML frontmatter carrying the description, which drives the picker
#         (code.claude.com/docs/en/slash-commands). The broz: prefix comes from
#         the commands/broz/ subdirectory, not from the filename.
# cursor: plain markdown, no frontmatter -- Cursor commands are prompt files
#         with no frontmatter contract (cursor.com/docs). It has no
#         subdirectory namespacing, so the broz- prefix goes in the filename.
render() {
  local src="$1" style="$2" desc body
  desc="$(head -1 "$src" | sed 's/"/'"'"'/g')"
  body="$(tail -n +2 "$src")"
  case "$style" in
    claude) printf -- '---\ndescription: "%s"\n---\n%s\n\n%s\n' "$desc" "$body" "$MARKER" ;;
    cursor) printf -- '%s\n%s\n\n%s\n' "$desc" "$body" "$MARKER" ;;
    *) echo "unknown style: $style" >&2; return 1 ;;
  esac
}

# Installed filename for one source command under one style.
destname() {
  local base="$1" style="$2"
  case "$style" in
    claude) echo "$base" ;;
    cursor) echo "broz-$base" ;;
  esac
}

write_one() {
  local want="$1" dest="$2"
  if [[ ! -f "$dest" ]]; then
    if [[ $CHECK -eq 1 ]]; then echo "  MISSING $dest"; drift=$((drift+1)); return 2; fi
    printf '%s\n' "$want" > "$dest"; return 0
  fi
  [[ "$(cat "$dest")" == "$want" ]] && return 1
  if grep -qF "$MARKER" "$dest" || [[ $FORCE -eq 1 ]]; then
    if [[ $CHECK -eq 1 ]]; then echo "  STALE   $dest"; drift=$((drift+1)); return 2; fi
    printf '%s\n' "$want" > "$dest"; return 0
  fi
  # No marker and not identical: a hand-written shim. Leave it.
  echo "  keep    $dest (hand-edited; --force to overwrite)"
  return 1
}

install_commands() {
  while IFS=$'\t' read -r id name style dir skdir; do
    [[ -z "${id:-}" || "$id" == \#* ]] && continue
    [[ "${dir:-}" == "-" || -z "${dir:-}" ]] && continue
    dir="${dir/#\~/$HOME}"
    if [[ ! -d "$(dirname "$dir")" ]]; then
      echo "  skip    $name commands -- $(dirname "$dir") does not exist"; continue
    fi
    [[ $CHECK -eq 1 ]] || mkdir -p "$dir"
    local n_w=0 n_k=0
    for src in "$SRC"/*.md; do
      local dest="$dir/$(destname "$(basename "$src")" "$style")"
      if write_one "$(render "$src" "$style")" "$dest"; then n_w=$((n_w+1)); else n_k=$((n_k+1)); fi
    done
    [[ $CHECK -eq 1 ]] || echo "  $name commands -> $dir  (written $n_w, unchanged $n_k)"
  done < "$CONF"
}

# Skills named in skills.conf are copied wholesale into <skills dir>/<group>/.
# Only those names are touched: a target's skills dir also holds standalone
# skills that have nothing to do with Broz OS and must never be collateral.
install_skills() {
  [[ -f "$SKCONF" ]] || return 0
  while IFS=$'\t' read -r id name style dir skdir; do
    [[ -z "${id:-}" || "$id" == \#* ]] && continue
    [[ "${skdir:-}" == "-" || -z "${skdir:-}" ]] && continue
    skdir="${skdir/#\~/$HOME}"
    [[ -d "$(dirname "$skdir")" ]] || { echo "  skip    $name skills -- $(dirname "$skdir") does not exist"; continue; }
    local n_s=0 n_ok=0
    while IFS=$'\t' read -r skill group; do
      [[ -z "${skill:-}" || "$skill" == \#* ]] && continue
      local src="$BROZ_HOME/skills/$skill" dest="$skdir/${group:+$group/}$skill"
      [[ -d "$src" ]] || { echo "  WARN    no such skill in repo: $skill"; continue; }
      if [[ -d "$dest" ]] && diff -rq "$src" "$dest" >/dev/null 2>&1; then n_ok=$((n_ok+1)); continue; fi
      if [[ $CHECK -eq 1 ]]; then echo "  STALE   $dest"; drift=$((drift+1)); continue; fi
      mkdir -p "$skdir"; rm -rf "$dest"; cp -R "$src" "$dest"; n_s=$((n_s+1))
    done < "$SKCONF"
    [[ $CHECK -eq 1 ]] || echo "  $name skills   -> $skdir  (synced $n_s, unchanged $n_ok)"
  done < "$CONF"
}

# The rules tree is one shared content tree read in place, not a per-tool
# artifact, so Cursor gets a symlink rather than a copy. Cursor reads project
# rules from .cursor/rules as .mdc files (cursor.com/docs/context/rules).
# Relative target: never dangles the way US-018's absolute symlinks did.
link_rules() {
  local link="$HOME/.cursor/rules/broz" want="../../.slopdog/rules/broz"
  [[ -d "$HOME/.cursor" ]] || { echo "  skip    rules symlink -- ~/.cursor does not exist"; return; }
  if [[ -L "$link" ]]; then
    [[ "$(readlink "$link")" == "$want" ]] && { echo "  rules    ~/.cursor/rules/broz -> $want (ok)"; return; }
    [[ $CHECK -eq 1 ]] && { echo "  WRONG   $link -> $(readlink "$link")"; drift=$((drift+1)); return; }
    rm "$link"
  elif [[ -e "$link" ]]; then
    echo "  keep    $link is a real directory, not touching it"; return
  fi
  [[ $CHECK -eq 1 ]] && { echo "  MISSING $link"; drift=$((drift+1)); return; }
  mkdir -p "$(dirname "$link")"; ln -s "$want" "$link"
  echo "  rules    ~/.cursor/rules/broz -> $want (created)"
}

install_commands
install_skills
link_rules

if [[ $CHECK -eq 1 ]]; then
  [[ $drift -eq 0 ]] && { echo; echo "in sync"; exit 0; }
  echo; echo "$drift item(s) out of sync -- run ./install.sh"; exit 1
fi
echo; echo "done"
