#!/usr/bin/env python3
"""
harvest_prompts.py — pull the HUMAN side of a Claude Code session out of the
transcript log and format it for a git commit message.

WHY THIS EXISTS
---------------
A git commit records WHAT changed and WHEN it landed. It does not record when
the DECISION was made, or what that decision superseded. When several sessions
run against the same repo in the same afternoon — opened 1, 2, 3 and closed
2, 3, 1 — commit order tells you nothing about instruction order, and a merge
conflict becomes a coin flip.

Embedding the operator's own timestamped prompts in the commit body fixes that:
whoever resolves the merge later can read, in wall-clock order, what was
actually asked for on each side, and apply "the LATEST instruction on this
topic wins" instead of "whichever branch merged last wins".

WHERE THE DATA COMES FROM
-------------------------
Claude Code writes one JSONL file per session under

    ~/.claude/projects/<slugified-cwd>/<session-uuid>.jsonl

One JSON object per line. The lines we care about look like:

    {"type": "user", "timestamp": "2026-08-18T03:58:51.925Z",
     "cwd": "/path/to/worktree", "gitBranch": "claude/foo-1234",
     "sessionId": "...", "message": {"role": "user", "content": "..."} }

Not every `type: user` line is a human typing. The same channel carries tool
results, skill preambles, and harness notices. Everything this script skips is
listed in `is_human_prompt()` below.

USAGE
-----
    python3 harvest_prompts.py                      # commit-ready block, auto window
    python3 harvest_prompts.py --since 2026-08-18T00:00:00Z
    python3 harvest_prompts.py --format json        # machine-readable
    python3 harvest_prompts.py --repo /path/to/repo --branch main

Exit code 0 always (an empty harvest is a normal outcome, not a failure).
Diagnostics go to stderr so stdout stays pasteable straight into a commit.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
from datetime import datetime, timedelta, timezone
from pathlib import Path

PROJECTS_DIR = Path.home() / ".claude" / "projects"

# Wrappers the harness injects around, or instead of, real human text.
_SYSTEM_REMINDER = re.compile(r"<system-reminder>.*?</system-reminder>", re.S)
_LOCAL_STDOUT = re.compile(r"<local-command-stdout>.*?</local-command-stdout>", re.S)
_LOCAL_CAVEAT = re.compile(r"<local-command-caveat>.*?</local-command-caveat>", re.S)
_CMD_MESSAGE = re.compile(r"<command-message>.*?</command-message>", re.S)
_CMD_ARGS = re.compile(r"<command-args>\s*</command-args>", re.S)
_CMD_NAME = re.compile(r"<command-name>(.*?)</command-name>", re.S)
_BLANKS = re.compile(r"\n{3,}")

# Boilerplate the harness emits as a bare user turn; carries no intent.
_NOISE_PREFIXES = (
    "Shell cwd was reset to",
    "Base directory for this skill:",
    "Caveat: The messages below were generated by the user",
    "[Request interrupted",
    "API Error",
)


# --------------------------------------------------------------------------
# git helpers
# --------------------------------------------------------------------------
def git(repo: Path, *args: str) -> str:
    """Run a git command in `repo` and return stripped stdout ('' on failure)."""
    try:
        out = subprocess.run(
            ["git", "-C", str(repo), *args],
            capture_output=True, text=True, check=True,
        )
        return out.stdout.strip()
    except (subprocess.CalledProcessError, FileNotFoundError):
        return ""


def default_window_start(repo: Path, branch: str) -> str | None:
    """
    Work out how far back "this piece of work" reaches.

    Preference order:
      1. The tip commit already on this branch — everything since then is new,
         uncommitted work, so its conversation belongs to the NEXT commit.
      2. The fork point from the default branch — covers the first commit on a
         fresh worktree branch, whose whole session is one unit of work.
      3. 12 hours ago — last resort, so a detached or brand-new repo still
         produces something rather than nothing.
    """
    for base_ref in ("HEAD", ):
        # Has this branch got commits of its own beyond the fork point?
        fork = ""
        for main_name in ("main", "master"):
            fork = git(repo, "merge-base", main_name, base_ref)
            if fork:
                break
        head = git(repo, "rev-parse", base_ref)
        if head and fork and head != fork:
            # Branch has its own commits — start from the newest one.
            when = git(repo, "log", "-1", "--format=%cI", base_ref)
            if when:
                return when
        if fork:
            when = git(repo, "log", "-1", "--format=%cI", fork)
            if when:
                return when
        if head:
            when = git(repo, "log", "-1", "--format=%cI", base_ref)
            if when:
                return when
    return (datetime.now(timezone.utc) - timedelta(hours=12)).isoformat()


# --------------------------------------------------------------------------
# transcript discovery
# --------------------------------------------------------------------------
def slugify_path(p: str) -> str:
    """
    Reproduce Claude Code's project-directory naming: every character that is
    not a letter or digit becomes a hyphen. '~/My Repo/.claude' →
    '-home-broz-My-Repo--claude'.
    """
    return re.sub(r"[^A-Za-z0-9]", "-", p)


def candidate_transcripts(tree: Path, since: datetime) -> list[Path]:
    """
    Transcript files worth opening.

    The slugged directory for this working tree is the fast path. If it does
    not exist (repo moved, or the session ran from a subdirectory) fall back to
    scanning every project directory — the per-entry `cwd` filter downstream
    keeps the result correct either way.
    """
    if not PROJECTS_DIR.is_dir():
        return []

    exact = PROJECTS_DIR / slugify_path(str(tree))
    dirs = [exact] if exact.is_dir() else list(PROJECTS_DIR.iterdir())

    files: list[Path] = []
    cutoff = (since - timedelta(days=1)).timestamp()
    for d in dirs:
        if not d.is_dir():
            continue
        for f in d.glob("*.jsonl"):
            # A session that was last written to before the window opened
            # cannot contain a prompt inside it.
            try:
                if f.stat().st_mtime >= cutoff:
                    files.append(f)
            except OSError:
                continue
    return files


# --------------------------------------------------------------------------
# entry filtering
# --------------------------------------------------------------------------
def clean_text(raw: str) -> str:
    """Strip harness wrappers, leaving what the human actually said."""
    t = _SYSTEM_REMINDER.sub("", raw)
    t = _LOCAL_STDOUT.sub("", t)
    t = _LOCAL_CAVEAT.sub("", t)
    t = _CMD_MESSAGE.sub("", t)
    t = _CMD_ARGS.sub("", t)
    # A slash command is real intent — keep it, just drop the XML around it.
    t = _CMD_NAME.sub(lambda m: m.group(1).strip(), t)
    t = _BLANKS.sub("\n\n", t)
    return t.strip()


def message_text(msg: dict) -> str | None:
    """
    Extract text from a message, or None if this turn is not human prose.

    Content arrives either as a plain string or as a list of typed blocks. A
    list containing a `tool_result` block is the harness feeding output back in,
    never a person typing.
    """
    content = msg.get("content")
    if isinstance(content, str):
        return content
    if not isinstance(content, list):
        return None
    parts = []
    for block in content:
        if not isinstance(block, dict):
            continue
        if block.get("type") == "tool_result":
            return None
        if block.get("type") == "text":
            parts.append(block.get("text", ""))
    return "\n".join(parts) if parts else None


def is_human_prompt(entry: dict) -> bool:
    """True only for a turn a person actually typed or dictated."""
    if entry.get("type") != "user":
        return False
    if entry.get("isMeta"):            # skill preambles, cwd notices
        return False
    if entry.get("isSidechain"):       # subagent conversations
        return False
    if entry.get("sourceToolUseID"):   # emitted by a tool, not a person
        return False
    if "toolUseResult" in entry:       # tool output echoed onto the user channel
        return False
    return True


def parse_ts(value: str | None) -> datetime | None:
    if not value:
        return None
    try:
        return datetime.fromisoformat(value.replace("Z", "+00:00"))
    except ValueError:
        return None


def harvest(tree: Path, branch: str, since: datetime, until: datetime,
            session: str | None) -> list[dict]:
    """Collect every human prompt for this tree/branch inside the time window."""
    found: list[dict] = []
    seen: set[tuple] = set()

    tree_str = str(tree.resolve())

    for path in candidate_transcripts(tree, since):
        try:
            fh = path.open(encoding="utf-8", errors="replace")
        except OSError:
            continue
        with fh:
            for line in fh:
                line = line.strip()
                if not line:
                    continue
                try:
                    entry = json.loads(line)
                except json.JSONDecodeError:
                    continue
                if not is_human_prompt(entry):
                    continue

                ts = parse_ts(entry.get("timestamp"))
                if ts is None or not (since <= ts <= until):
                    continue

                # A session may span more than one tree; filter per entry.
                cwd = entry.get("cwd")
                if cwd and not str(Path(cwd).resolve()).startswith(tree_str):
                    continue
                entry_branch = entry.get("gitBranch")
                if branch and entry_branch and entry_branch != branch:
                    continue
                if session and entry.get("sessionId") != session:
                    continue

                raw = message_text(entry.get("message", {}))
                if raw is None:
                    continue
                text = clean_text(raw)
                if not text or text.startswith(_NOISE_PREFIXES):
                    continue

                key = (ts.isoformat(), text[:120])
                if key in seen:      # same session resumed into a second file
                    continue
                seen.add(key)

                found.append({
                    "ts": ts,
                    "text": text,
                    "session": entry.get("sessionId", ""),
                    "branch": entry_branch or branch,
                })

    found.sort(key=lambda p: p["ts"])
    return found


# --------------------------------------------------------------------------
# rendering
# --------------------------------------------------------------------------
def truncate(text: str, limit: int) -> str:
    if len(text) <= limit:
        return text
    return text[:limit].rstrip() + f"\n    […truncated, {len(text) - limit} more chars]"


def render_commit_block(prompts: list[dict], branch: str, max_prompt: int,
                        max_total: int) -> str:
    """
    Render the block that goes into the commit body.

    Shape matters — `merge_timeline.py` parses it back out, and the marker line
    is what lets it tell a conversation block from ordinary prose:

        --- Conversation (N prompts, first → last) ---

        [2026-08-18 05:02 UTC] broz:
        the prompt text, indented two spaces

    Trailing git trailers (Session-Id: etc.) are appended by the caller.
    """
    if not prompts:
        return ""

    first = prompts[0]["ts"].strftime("%Y-%m-%d %H:%M UTC")
    last = prompts[-1]["ts"].strftime("%Y-%m-%d %H:%M UTC")
    head = f"--- Conversation ({len(prompts)} prompts, {first} → {last}) ---"

    lines = [head, ""]
    budget = max_total
    dropped = 0
    for p in prompts:
        body = truncate(p["text"], max_prompt)
        stamp = p["ts"].strftime("%Y-%m-%d %H:%M UTC")
        chunk = f"[{stamp}] broz:\n" + "\n".join(
            "  " + ln if ln.strip() else "" for ln in body.splitlines()
        )
        if len(chunk) > budget:
            dropped += 1
            continue
        budget -= len(chunk) + 2
        lines.append(chunk)
        lines.append("")

    if dropped:
        lines.append(f"[{dropped} further prompt(s) omitted — total-size cap reached; "
                     f"full record in the session transcript]")
        lines.append("")

    return "\n".join(lines).rstrip()


def render_trailers(prompts: list[dict]) -> str:
    """
    Git trailers: one block, no blank lines inside, at the very end of the body.
    These are what tooling greps for; the prose block above is for humans.
    """
    if not prompts:
        return ""
    sessions = sorted({p["session"] for p in prompts if p["session"]})
    first = prompts[0]["ts"].strftime("%Y-%m-%dT%H:%M:%SZ")
    last = prompts[-1]["ts"].strftime("%Y-%m-%dT%H:%M:%SZ")
    out = [
        f"Conversation-Window: {first}/{last}",
        f"Prompt-Count: {len(prompts)}",
    ]
    for s in sessions:
        out.append(f"Session-Id: {s}")
    return "\n".join(out)


# --------------------------------------------------------------------------
def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--repo", default=".", help="working tree (default: cwd)")
    ap.add_argument("--branch", default=None, help="branch filter (default: current)")
    ap.add_argument("--since", default=None, help="ISO8601 window start (default: auto)")
    ap.add_argument("--until", default=None, help="ISO8601 window end (default: now)")
    ap.add_argument("--session", default=None,
                    help="restrict to one session id (default: all matching this branch)")
    # Voice-dictated prompts run long, and the tail is usually where the
    # actual instruction lands. Cap generously — a truncated intent defeats
    # the point of recording it at all.
    ap.add_argument("--max-prompt-chars", type=int, default=3000)
    ap.add_argument("--max-total-chars", type=int, default=24000)
    ap.add_argument("--format", choices=("commit", "plain", "json"), default="commit")
    args = ap.parse_args()

    tree_root = git(Path(args.repo), "rev-parse", "--show-toplevel")
    tree = Path(tree_root) if tree_root else Path(args.repo).resolve()
    branch = args.branch or git(tree, "branch", "--show-current")

    since = parse_ts(args.since) or parse_ts(default_window_start(tree, branch))
    if since is None:
        since = datetime.now(timezone.utc) - timedelta(hours=12)
    until = parse_ts(args.until) or datetime.now(timezone.utc)

    prompts = harvest(tree, branch, since, until, args.session)

    print(f"harvest: tree={tree} branch={branch or '(none)'} "
          f"window={since.isoformat()} → {until.isoformat()} "
          f"prompts={len(prompts)}", file=sys.stderr)

    if args.format == "json":
        print(json.dumps([
            {"timestamp": p["ts"].isoformat(), "session": p["session"],
             "branch": p["branch"], "text": p["text"]}
            for p in prompts
        ], indent=2))
        return 0

    block = render_commit_block(prompts, branch,
                                args.max_prompt_chars, args.max_total_chars)
    if args.format == "plain":
        print(block)
        return 0

    if block:
        print(block)
        print()
        print(render_trailers(prompts))
    return 0


if __name__ == "__main__":
    sys.exit(main())
